### PR TITLE
py-winrm-plugin dependency auto install (except kerberos)

### PR DESCRIPTION
**Pull request by G3NSVRV**
py-winrm-plugin dependency auto install (except kerberos)

_**disclaimer**: it fails the first time because for some reason does not take the **WINRM_INSTALLED** validity check, but the second time works as a charm_

### CODE REVIEW

**Comment by fdevans** [comment]
Added a ticket to review this, but please fix conflicts when possible.

**Comment by chrismcg14** [comment]
This looks good, but the conflicts still need to be resolved

**Comment by G3NSVRV** [comment]
@chrismcg14 please check if that works now.

**Comment by ellisgeek** [comment]
This would not work on ubuntu 24.04 as the pip will not install packages in the system interpreter by default and using the `break-system-packages` flag is not advisable. I would suggest creating a virtualenv with the required packages installed and pointing the plugin interpreter at that instead.

**Comment by G3NSVRV** [comment]
@ellisgeek yep, indeed. I have tested this update on the Docker image of rundeckpro-enterprise which is based on ubuntu, but it seems that behaves really different than the standalone version; I have tested the standalone version, and I got the `pyenv` warning everywhere, so... really sad to say, but this update could break everything on ubuntu.

**Pull request closed without merging**
