### PR TITLE
RUN-1290: Interpreter select + update build

### PR DESCRIPTION
**Pull request by qualman**
This PR removes the ability to freely input the name of your python interpreter, for security reasons. It also updates Gradle to 7.4.2, and removes reliance on the rundeck-plugins/build-zip build gradle by pulling that configuration in locally.

### CODE REVIEW

**Comment by ltamaster** [comment]
Hi @qualman 
The PR that added this feature has the idea to support `virtualenv`: https://github.com/rundeck-plugins/py-winrm-plugin/pull/35

So I am wondering if we can add a second field with the interpreter path and concatenate that with the python interpreter: like `script-interpreter: ${config.interpreterPath}/${config.interpreter} -u` 

(Not sure if that works)

**Comment by qualman** [comment]
I see. I added that exact thing at first, but then my worry was that they could use the path field to actually target a binary instead.

I think there would be a way to check against that (no spaces, enforce slashes, etc.) but the script plugins don't allow for that kind of logic afaik. I also just had more basic issues like removing the slash between vars when the path was empty because of the lack of scripting abilities on the properties.

So it seemed easier to ask them to keep the binaries in their path instead and be a bit more restrictive. Thoughts @ltamaster ?

**Comment by ltamaster** [comment]
you are right, I guess there is no other option that a fixed list

**Comment by qualman** [comment]
Darn, ok thanks Luis. I appreciate your review all the same.

**Comment by qualman** [comment]
Here is how it looks now, and the output (it is failing, but it is correctly calling the selected `python3`)
Screen Shot 2022-10-26 at 16 17 44
Screen Shot 2022-10-26 at 16 17 20

**Review by ltamaster — APPROVED** [review]
tested, worked as expected

**Pull request merged**
